# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dht_network_pb2 as dht__network__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dht_network_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DhtServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutFile = channel.unary_unary(
                '/DhtService/PutFile',
                request_serializer=dht__network__pb2.FileRequest.SerializeToString,
                response_deserializer=dht__network__pb2.FileResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/DhtService/GetFile',
                request_serializer=dht__network__pb2.FileRequest.SerializeToString,
                response_deserializer=dht__network__pb2.FileResponse.FromString,
                _registered_method=True)
        self.LookupFile = channel.unary_unary(
                '/DhtService/LookupFile',
                request_serializer=dht__network__pb2.FileRequest.SerializeToString,
                response_deserializer=dht__network__pb2.LocationResponse.FromString,
                _registered_method=True)
        self.JoinNetwork = channel.unary_unary(
                '/DhtService/JoinNetwork',
                request_serializer=dht__network__pb2.JoinRequest.SerializeToString,
                response_deserializer=dht__network__pb2.Confirmation.FromString,
                _registered_method=True)
        self.LeaveNetwork = channel.unary_unary(
                '/DhtService/LeaveNetwork',
                request_serializer=dht__network__pb2.LeaveRequest.SerializeToString,
                response_deserializer=dht__network__pb2.Confirmation.FromString,
                _registered_method=True)


class DhtServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PutFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DhtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=dht__network__pb2.FileRequest.FromString,
                    response_serializer=dht__network__pb2.FileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=dht__network__pb2.FileRequest.FromString,
                    response_serializer=dht__network__pb2.FileResponse.SerializeToString,
            ),
            'LookupFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupFile,
                    request_deserializer=dht__network__pb2.FileRequest.FromString,
                    response_serializer=dht__network__pb2.LocationResponse.SerializeToString,
            ),
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=dht__network__pb2.JoinRequest.FromString,
                    response_serializer=dht__network__pb2.Confirmation.SerializeToString,
            ),
            'LeaveNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveNetwork,
                    request_deserializer=dht__network__pb2.LeaveRequest.FromString,
                    response_serializer=dht__network__pb2.Confirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DhtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DhtService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DhtService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DhtService/PutFile',
            dht__network__pb2.FileRequest.SerializeToString,
            dht__network__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DhtService/GetFile',
            dht__network__pb2.FileRequest.SerializeToString,
            dht__network__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DhtService/LookupFile',
            dht__network__pb2.FileRequest.SerializeToString,
            dht__network__pb2.LocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DhtService/JoinNetwork',
            dht__network__pb2.JoinRequest.SerializeToString,
            dht__network__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DhtService/LeaveNetwork',
            dht__network__pb2.LeaveRequest.SerializeToString,
            dht__network__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
