# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dht_network.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dht_network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ht_network.proto\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"0\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"5\n\x10LocationResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"8\n\x0bJoinRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x1f\n\x0cLeaveRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"0\n\x0c\x43onfirmation\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe5\x01\n\nDhtService\x12&\n\x07PutFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12&\n\x07GetFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12-\n\nLookupFile\x12\x0c.FileRequest\x1a\x11.LocationResponse\x12*\n\x0bJoinNetwork\x12\x0c.JoinRequest\x1a\r.Confirmation\x12,\n\x0cLeaveNetwork\x12\r.LeaveRequest\x1a\r.Confirmationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dht_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=21
  _globals['_FILEREQUEST']._serialized_end=69
  _globals['_FILERESPONSE']._serialized_start=71
  _globals['_FILERESPONSE']._serialized_end=119
  _globals['_LOCATIONRESPONSE']._serialized_start=121
  _globals['_LOCATIONRESPONSE']._serialized_end=174
  _globals['_JOINREQUEST']._serialized_start=176
  _globals['_JOINREQUEST']._serialized_end=232
  _globals['_LEAVEREQUEST']._serialized_start=234
  _globals['_LEAVEREQUEST']._serialized_end=265
  _globals['_CONFIRMATION']._serialized_start=267
  _globals['_CONFIRMATION']._serialized_end=315
  _globals['_DHTSERVICE']._serialized_start=318
  _globals['_DHTSERVICE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
