# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"&\n\x0c\x46ileResponse\x12\x16\n\x0enode_addresses\x18\x01 \x03(\t\"#\n\x0bJoinRequest\x12\x14\n\x0cnode_address\x18\x01 \x01(\t\"\x1f\n\x0cJoinResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x0cLeaveRequest\x12\x14\n\x0cnode_address\x18\x01 \x01(\t\" \n\rLeaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x7f\n\x07P2PNode\x12\'\n\x08\x46indFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12#\n\x04Join\x12\x0c.JoinRequest\x1a\r.JoinResponse\x12&\n\x05Leave\x12\r.LeaveRequest\x1a\x0e.LeaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=13
  _globals['_FILEREQUEST']._serialized_end=44
  _globals['_FILERESPONSE']._serialized_start=46
  _globals['_FILERESPONSE']._serialized_end=84
  _globals['_JOINREQUEST']._serialized_start=86
  _globals['_JOINREQUEST']._serialized_end=121
  _globals['_JOINRESPONSE']._serialized_start=123
  _globals['_JOINRESPONSE']._serialized_end=154
  _globals['_LEAVEREQUEST']._serialized_start=156
  _globals['_LEAVEREQUEST']._serialized_end=192
  _globals['_LEAVERESPONSE']._serialized_start=194
  _globals['_LEAVERESPONSE']._serialized_end=226
  _globals['_P2PNODE']._serialized_start=228
  _globals['_P2PNODE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
